### ISSUE TITLE
Please provide support for WSDL and RAML

### ISSUE THREAD

**Issue by bryan-yongwon-kwon** [kloudtek/mule4-api-archetype#7]
To create a soap service in Mule 4, we have to provide the WSDL when the project is created. This means mule4-api-archetype cannot be used to create SOAP APIs. It would be nice for this archetype to create the flows for the methods automatically with provided service definition file.

**Comment by ymenager** [comment]
definitely not possible I'm afraid.... maven archetypes have extremely limited templating capabilities, do it wouldn't be able to do something like parsing WSDL and dynamically generating file content
